=== deer/netzo/scripts/item.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "uid": {
      "type": "string",
      "pattern": "^(resource-|template-).*"
    },
    "type": {
      "type": "string",
      "enum": [
        "resource",
        "template"
      ]
    },
    "version": {
      "type": "string",
      "pattern": "(0-9)*.(0-9)*.(0-9)*."
    },
    "status": {
      "type": "string",
      "enum": [
        "published",
        "requested"
      ]
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string",
      "maxLength": 250
    },
    "labels": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "display": {
      "type": "object",
      "properties": {
        "imageUrl": {
          "type": "string",
          "format": "uri"
        },
        "color": {
          "type": "string",
          "format": "hexcolor"
        }
      },
      "required": [
        "imageUrl"
      ]
    },
    "links": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "rel": {
              "type": "string"
            },
            "href": {
              "type": "string",
              "format": "uri"
            },
            "title": {
              "type": "string"
            },
            "type": {
              "type": "string"
            }
          },
          "required": [
            "rel",
            "href"
          ]
        }
      ]
    },
    "schema": {
      "type": "array",
      "items": {}
    },
    "item": {
      "type": "object",
      "properties": {}
    }
  }
}

=== deer/netzo/packages/resources/resource-http-discord/item.json
{
  "uid": "resource-http-discord",
  "type": "resource",
  "status": "published",
  "name": "Discord",
  "description": "Resource for the Discord API",
  "labels": [
    "social",
    "communications"
  ],
  "display": {
    "imageUrl": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-discord/icon.webp"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/resources/resource-http-discord"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-discord/src/readme.md"
    }
  ],
  "item": {
    "_type": "resource",
    "type": "http",
    "base": {
      "baseURL": "https://discord.com/api/v10",
      "headers": {
        "Content-Type": "application/json"
      },
      "authorization": {
        "type": "apiKey",
        "in": "header",
        "name": "Authorization",
        "value": "{{tokenType}} {{token}}"
      }
    }
  }
}

=== deer/netzo/packages/resources/resource-http-purpleair/item.json
{
  "uid": "resource-http-purpleair",
  "type": "resource",
  "status": "published",
  "name": "PurpleAir",
  "description": "Resource for the PurpleAir API",
  "labels": [
    "iot",
    "environmental"
  ],
  "display": {
    "imageUrl": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-purpleair/icon.webp"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/resources/resource-http-purpleair"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-purpleair/src/readme.md"
    }
  ],
  "schema": [
    {
      "component": "v-text-field",
      "name": "apiKey",
      "label": "API Key"
    }
  ],
  "item": {
    "_type": "resource",
    "type": "http",
    "base": {
      "baseURL": "https://api.purpleair.com/v1",
      "headers": {
        "Content-Type": "application/json"
      },
      "authorization": {
        "type": "apiKey",
        "in": "header",
        "name": "X-API-Key",
        "value": "{{apiKey}}"
      }
    }
  }
}

=== deer/netzo/packages/resources/resource-http-enode/item.json
{
  "uid": "resource-http-enode",
  "type": "resource",
  "status": "requested",
  "name": "Enode",
  "description": "Resource for the Enode API",
  "labels": [
    "iot",
    "energy",
    "solar"
  ],
  "display": {
    "imageUrl": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-enode/icon.webp"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/resources/resource-http-enode"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-enode/src/readme.md"
    }
  ],
  "item": {
    "_type": "resource",
    "type": "http",
    "base": {
      "baseURL": "https://enode-api.production.enode.io",
      "headers": {
        "Content-Type": "application/json"
      },
      "authorization": {
        "type": "oauth2",
        "clientId": "{{clientId}}",
        "clientSecret": "{{clientSecret}}",
        "authorizationURL": "{{authorizationURL}}",
        "accessTokenURL": "{{accessTokenURL}}",
        "redirectURL": "{{redirectURL}}",
        "scopes": "{{scopes}}"
      }
    }
  }
}

=== deer/netzo/packages/resources/resource-http-netzo/item.json
{
  "uid": "resource-http-netzo",
  "type": "resource",
  "status": "published",
  "name": "Netzo",
  "description": "Resource for the Netzo API",
  "labels": [
    "infrastructure",
    "integrations",
    "admin"
  ],
  "display": {
    "imageUrl": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-netzo/icon.webp"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/resources/resource-http-netzo"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-netzo/src/readme.md"
    }
  ],
  "schema": [
    {
      "component": "v-text-field",
      "name": "apiKey",
      "label": "API Key"
    }
  ],
  "item": {
    "_type": "resource",
    "type": "http",
    "base": {
      "baseURL": "https://api.netzo.io",
      "headers": {
        "Content-Type": "application/json"
      },
      "authorization": {
        "type": "apiKey",
        "in": "header",
        "name": "x-api-key",
        "value": "{{apiKey}}"
      }
    }
  }
}

=== deer/netzo/packages/resources/resource-http-enphase/item.json
{
  "uid": "resource-http-enphase",
  "type": "resource",
  "status": "requested",
  "name": "Enphase",
  "description": "Resource for the Enphase API",
  "labels": [
    "iot",
    "energy",
    "solar"
  ],
  "display": {
    "imageUrl": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-enphase/icon.webp"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/resources/resource-http-enphase"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-enphase/src/readme.md"
    }
  ],
  "item": {
    "_type": "resource",
    "type": "http",
    "base": {
      "baseURL": "https://api.enphaseenergy.com/api/v4",
      "headers": {
        "Content-Type": "application/json"
      },
      "authorization": {
        "type": "oauth2",
        "clientId": "{{clientId}}",
        "clientSecret": "{{clientSecret}}",
        "authorizationURL": "{{authorizationURL}}",
        "accessTokenURL": "{{accessTokenURL}}",
        "redirectURL": "{{redirectURL}}",
        "scopes": "{{scopes}}"
      }
    }
  }
}

=== deer/netzo/packages/resources/resource-http-spacexland/item.json
{
  "uid": "resource-http-spacexland",
  "type": "resource",
  "version": "1.0.0",
  "status": "published",
  "name": "SpaceX Land",
  "description": "Resource for the SpaceX Land GraphQL API",
  "labels": [
    "mock",
    "space"
  ],
  "display": {
    "imageUrl": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-spacexland/icon.webp"
  },
  "links": [
    {
      "rel": "author",
      "href": "https://netzo.io",
      "title": "Netzo"
    },
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/resources/resource-http-spacexland"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-spacexland/src/readme.md"
    }
  ],
  "schema": [
    {
      "component": "v-text-field",
      "name": "apiKey",
      "label": "API Key"
    }
  ],
  "item": {
    "_type": "resource",
    "type": "http",
    "base": {
      "baseURL": "https://api.spacexland.com/v2",
      "headers": {},
      "authorization": {
        "type": "apiKey",
        "in": "header",
        "name": "Authorization",
        "value": "{{apiKey}}"
      }
    }
  }
}

=== deer/netzo/packages/resources/resource-http-netzo-echo/item.json
{
  "uid": "resource-http-netzo-echo",
  "type": "resource",
  "status": "published",
  "name": "Netzo Echo",
  "description": "Resource for the Netzo Echo API (echoes back requests)",
  "labels": [
    "mock",
    "utility"
  ],
  "display": {
    "imageUrl": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-netzo-echo/icon.webp"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/resources/resource-http-netzo-echo"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-netzo-echo/src/readme.md"
    }
  ],
  "item": {
    "_type": "resource",
    "type": "http",
    "base": {
      "baseURL": "https://echo.netzo.io",
      "headers": {},
      "authorization": {}
    }
  }
}

=== deer/netzo/packages/templates/template-framework-ultrajs/item.json
{
  "uid": "template-framework-ultrajs",
  "type": "template",
  "version": "1.0.0",
  "status": "published",
  "name": "UltraJS",
  "description": "A basic starter template using the UltraJS library",
  "labels": [
    "framework"
  ],
  "display": {
    "imageUrl": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-ultrajs/icon.svg"
  },
  "links": [
    {
      "rel": "author",
      "href": "https://netzo.io",
      "title": "Netzo"
    },
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/templates/template-framework-ultrajs"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-ultrajs/src/readme.md"
    }
  ],
  "schema": [],
  "item": {
    "_type": "project",
    "fs": {
      "readme.md": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-ultrajs/src/readme.md"
      },
      "deno.jsonc": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-ultrajs/src/deno.jsonc"
      },
      "app.tsx": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-ultrajs/src/app.tss"
      },
      "server.tsx": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-ultrajs/src/server.tsx"
      }
    },
    "configuration": {
      "entrypoint": "server.tsx",
      "envs": {},
      "permissions": {
        "net": true
      }
    }
  }
}
