=== deer/netzo/scripts/item.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "uid": {
      "type": "string",
      "pattern": "^(resource-|template-).*"
    },
    "type": {
      "type": "string",
      "enum": [
        "resource",
        "template"
      ]
    },
    "version": {
      "type": "string",
      "pattern": "(0-9)*.(0-9)*.(0-9)*."
    },
    "status": {
      "type": "string",
      "enum": [
        "published",
        "requested"
      ]
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string",
      "maxLength": 250
    },
    "labels": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "display": {
      "type": "object",
      "properties": {
        "imageUrl": {
          "type": "string",
          "format": "uri"
        },
        "color": {
          "type": "string",
          "format": "hexcolor"
        }
      },
      "required": [
        "imageUrl"
      ]
    },
    "links": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "rel": {
              "type": "string"
            },
            "href": {
              "type": "string",
              "format": "uri"
            },
            "title": {
              "type": "string"
            },
            "type": {
              "type": "string"
            }
          },
          "required": [
            "rel",
            "href"
          ]
        }
      ]
    },
    "schema": {
      "type": "array",
      "items": {}
    },
    "item": {
      "type": "object",
      "properties": {}
    }
  }
}

=== deer/netzo/packages/templates/template-framework-fresh/item.json
{
  "uid": "template-framework-fresh",
  "type": "template",
  "version": "1.0.0",
  "status": "published",
  "name": "Fresh",
  "description": "A basic starting template using the Frash framework",
  "labels": [
    "framework"
  ],
  "display": {
    "imageUrl": "https://api.iconify.design/logos:fresh.svg"
  },
  "links": [
    {
      "rel": "author",
      "href": "https://netzo.io",
      "title": "Netzo"
    },
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/templates/template-framework-fresh"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-fresh/src/readme.md"
    }
  ],
  "schema": [],
  "item": {
    "_type": "project",
    "fs": {
      "readme.md": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-framework-fresh/src/readme.md"
      },
      "deno.jsonc": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-fresh/src/deno.jsonc"
      },
      "main.ts": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-fresh/src/main.ts"
      },
      "deno.json": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-fresh/src/deno.json"
      },
      "fresh.gen.ts": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-fresh/src/fresh.gen.ts"
      },
      "import_map.json": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-fresh/src/import_map.json"
      },
      "islands/Counter.tsx": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-fresh/src/islands/Counter.tsx"
      },
      "routes/index.tsx": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-fresh/src/routes/index.tsx"
      }
    },
    "configuration": {
      "entrypoint": "main.ts",
      "envs": {},
      "permissions": {
        "net": true
      }
    }
  }
}

=== deer/netzo/packages/resources/resource-http-zoho/item.json
{
  "uid": "resource-http-zoho",
  "type": "resource",
  "version": "1.0.0",
  "status": "requested",
  "name": "Zoho",
  "description": "Resource for the Zoho API",
  "labels": [
    "crm"
  ],
  "display": {
    "imageUrl": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-zoho/icon.webp"
  },
  "links": [
    {
      "rel": "author",
      "href": "https://netzo.io",
      "title": "Netzo"
    },
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/resources/resource-http-zoho"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-zoho/src/readme.md"
    }
  ],
  "schema": [
    {
      "component": "v-text-field",
      "name": "baseURL",
      "label": "Base URL",
      "hint": "Replace {{siteURL}} and {{versionNumber}} with corresponding values",
      "default": "https://{{siteURL}}/rest/v{{versionNumber}}"
    }
  ],
  "item": {
    "_type": "resource",
    "type": "http",
    "base": {
      "baseURL": "{{baseURL}}",
      "headers": {
        "Content-Type": "application/json"
      },
      "authorization": {
        "type": "oauth2",
        "clientId": "{{clientId}}",
        "clientSecret": "{{clientSecret}}",
        "authorizationURL": "{{authorizationURL}}",
        "accessTokenURL": "{{accessTokenURL}}",
        "redirectURL": "{{redirectURL}}",
        "scopes": "{{scopes}}"
      }
    }
  }
}

=== deer/netzo/packages/resources/resource-http-github/item.json
{
  "uid": "resource-http-github",
  "type": "resource",
  "status": "published",
  "name": "GitHub",
  "description": "Resource for the GitHub API",
  "labels": [
    "infrastructure"
  ],
  "display": {
    "imageUrl": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-github/icon.webp"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/resources/resource-http-github"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-github/src/readme.md"
    }
  ],
  "schema": [
    {
      "component": "v-text-field",
      "name": "personalAccessToken",
      "label": "Personal Access Token"
    }
  ],
  "item": {
    "_type": "resource",
    "type": "http",
    "base": {
      "baseURL": "https://api.github.com",
      "headers": {
        "Content-Type": "application/json"
      },
      "authorization": {
        "type": "bearer",
        "token": "{{personalAccessToken}}"
      }
    }
  }
}

=== deer/netzo/packages/resources/resource-http-rappi/item.json
{
  "uid": "resource-http-rappi",
  "type": "resource",
  "status": "requested",
  "name": "Rappi",
  "description": "Rappi is an application for ordering food and other products from local stores.",
  "labels": [
    "delivery"
  ],
  "display": {
    "imageUrl": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-rappi/icon.webp"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/resources/resource-http-rappi"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-rappi/src/readme.md"
    }
  ],
  "schema": [
    {
      "component": "v-text-field",
      "name": "clientId",
      "label": "Client ID"
    },
    {
      "component": "v-text-field",
      "name": "clientSecret",
      "label": "Client Secret"
    },
    {
      "component": "v-text-field",
      "name": "authorizationURL",
      "label": "Authorization URL"
    },
    {
      "component": "v-text-field",
      "name": "accessTokenURL",
      "label": "Access Token URL"
    },
    {
      "component": "v-text-field",
      "name": "redirectURL",
      "label": "Redirect URL"
    },
    {
      "component": "v-combobox",
      "name": "scopes",
      "label": "Scopes",
      "chips": true,
      "multiple": true
    }
  ],
  "item": {
    "_type": "resource",
    "type": "http",
    "base": {
      "baseURL": "https://api.rappi.com/2",
      "headers": {
        "Content-Type": "application/json"
      },
      "authorization": {
        "type": "oauth2",
        "clientId": "{{clientId}}",
        "clientSecret": "{{clientSecret}}",
        "authorizationURL": "{{authorizationURL}}",
        "accessTokenURL": "{{accessTokenURL}}",
        "redirectURL": "{{redirectURL}}",
        "scopes": "{{scopes}}"
      }
    }
  }
}

=== deer/netzo/packages/resources/resource-http-sendgrid/item.json
{
  "uid": "resource-http-sendgrid",
  "type": "resource",
  "status": "published",
  "name": "Sendgrid",
  "description": "Resource for the Sendgrid API",
  "labels": [
    "transactional",
    "communications"
  ],
  "display": {
    "imageUrl": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-sendgrid/icon.webp"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/resources/resource-http-sendgrid"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-sendgrid/src/readme.md"
    }
  ],
  "item": {
    "_type": "resource",
    "type": "http",
    "base": {
      "baseURL": "https://api.sendgrid.com/v3",
      "headers": {
        "Content-Type": "application/json"
      },
      "authorization": {
        "type": "apiKey",
        "in": "header",
        "name": "Authorization",
        "value": "Bearer {{apiKey}}"
      }
    }
  }
}

=== deer/netzo/packages/resources/resource-http-fathomanalytics/item.json
{
  "uid": "resource-http-fathomanalytics",
  "type": "resource",
  "version": "1.0.0",
  "status": "published",
  "name": "Fathom Analytics",
  "description": "Resource for the Fathom Analytics API",
  "labels": [
    "analytics"
  ],
  "display": {
    "imageUrl": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-fathomanalytics/icon.webp"
  },
  "links": [
    {
      "rel": "author",
      "href": "https://netzo.io",
      "title": "Netzo"
    },
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/resources/resource-http-fathomanalytics"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-fathomanalytics/src/readme.md"
    }
  ],
  "schema": [
    {
      "component": "v-text-field",
      "name": "apiToken",
      "label": "API Token"
    }
  ],
  "item": {
    "_type": "resource",
    "type": "http",
    "base": {
      "baseURL": "https://api.openai.com/v1",
      "headers": {
        "Content-Type": "application/json"
      },
      "authorization": {
        "type": "Bearer",
        "token": "{{apiToken}}"
      }
    }
  }
}

=== deer/netzo/packages/resources/resource-http-activecampaign/item.json
{
  "uid": "resource-http-activecampaign",
  "type": "resource",
  "status": "published",
  "name": "ActiveCampaign",
  "description": "Resource for the ActiveCampaign API",
  "labels": [
    "crm",
    "marketing"
  ],
  "display": {
    "imageUrl": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-activecampaign/icon.webp"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/resources/resource-http-activecampaign"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-activecampaign/src/readme.md"
    }
  ],
  "item": {
    "_type": "resource",
    "type": "http",
    "base": {
      "baseURL": "https://{{accountName}}.api-us1.com/api/3",
      "headers": {
        "Content-Type": "application/json"
      },
      "authorization": {
        "type": "apiKey",
        "in": "header",
        "name": "Api-Token",
        "value": "{{apiKey}}"
      }
    }
  }
}

=== deer/netzo/packages/resources/resource-http-sugarcrm/item.json
{
  "uid": "resource-http-sugarcrm",
  "type": "resource",
  "version": "1.0.0",
  "status": "requested",
  "name": "SugarCRM",
  "description": "Resource for the SugarCRM API",
  "labels": [
    "crm"
  ],
  "display": {
    "imageUrl": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-sugarcrm/icon.webp"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/resources/resource-http-sugarcrm"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-sugarcrm/src/readme.md"
    }
  ],
  "schema": [
    {
      "component": "v-text-field",
      "name": "baseURL",
      "label": "Base URL",
      "hint": "Replace {{siteURL}} with corresponding value",
      "default": "https://{{siteURL}}/rest/v11_17"
    },
    {
      "component": "v-text-field",
      "name": "clientId",
      "label": "Client ID"
    },
    {
      "component": "v-text-field",
      "name": "clientSecret",
      "label": "Client Secret"
    },
    {
      "component": "v-text-field",
      "name": "authorizationURL",
      "label": "Authorization URL"
    },
    {
      "component": "v-text-field",
      "name": "accessTokenURL",
      "label": "Access Token URL"
    },
    {
      "component": "v-text-field",
      "name": "redirectURL",
      "label": "Redirect URL"
    },
    {
      "component": "v-combobox",
      "name": "scopes",
      "label": "Scopes",
      "chips": true,
      "multiple": true
    }
  ],
  "item": {
    "_type": "resource",
    "type": "http",
    "base": {
      "baseURL": "{{baseURL}}",
      "headers": {
        "Content-Type": "application/json"
      },
      "authorization": {
        "type": "oauth2",
        "clientId": "{{clientId}}",
        "clientSecret": "{{clientSecret}}",
        "authorizationURL": "{{authorizationURL}}",
        "accessTokenURL": "{{accessTokenURL}}",
        "redirectURL": "{{redirectURL}}",
        "scopes": "{{scopes}}"
      }
    }
  }
}
