=== deer/netzo/scripts/item.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "uid": {
      "type": "string",
      "pattern": "^(resource-|template-).*"
    },
    "type": {
      "type": "string",
      "enum": [
        "resource",
        "template"
      ]
    },
    "version": {
      "type": "string",
      "pattern": "(0-9)*.(0-9)*.(0-9)*."
    },
    "status": {
      "type": "string",
      "enum": [
        "published",
        "requested"
      ]
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string",
      "maxLength": 250
    },
    "labels": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "display": {
      "type": "object",
      "properties": {
        "imageUrl": {
          "type": "string",
          "format": "uri"
        },
        "color": {
          "type": "string",
          "format": "hexcolor"
        }
      },
      "required": [
        "imageUrl"
      ]
    },
    "links": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "rel": {
              "type": "string"
            },
            "href": {
              "type": "string",
              "format": "uri"
            },
            "title": {
              "type": "string"
            },
            "type": {
              "type": "string"
            }
          },
          "required": [
            "rel",
            "href"
          ]
        }
      ]
    },
    "schema": {
      "type": "array",
      "items": {}
    },
    "item": {
      "type": "object",
      "properties": {}
    }
  }
}

=== deer/netzo/packages/resources/resource-http-hashnode/item.json
{
  "uid": "resource-http-hashnode",
  "type": "resource",
  "version": "1.0.0",
  "status": "requested",
  "name": "Hashnode",
  "description": "Resource for the Hashnode API",
  "labels": [
    "social",
    "blog"
  ],
  "display": {
    "imageUrl": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-hashnode/icon.webp"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/resources/resource-http-hashnode"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-hashnode/src/readme.md"
    }
  ],
  "schema": [
    {
      "component": "v-text-field",
      "name": "apiKey",
      "label": "API Key"
    }
  ],
  "item": {
    "_type": "resource",
    "type": "http",
    "base": {
      "baseURL": "https://hashnode.typicode.com",
      "headers": {
        "Content-Type": "application/json"
      },
      "authorization": {
        "type": "apiKey",
        "in": "header",
        "name": "Authorization",
        "value": "{{apiKey}}"
      }
    }
  }
}

=== deer/netzo/packages/templates/template-framework-netzo/item.json
{
  "uid": "template-framework-netzo",
  "type": "template",
  "status": "published",
  "name": "Netzo",
  "description": "An HTTP server using netzo that responds with different payload types based on route. Netzo includes a routing and utility library for Deno Deploy. Its route handler signature is simple and easy to understand. Handlers accept a Request and return a Response.",
  "labels": [
    "framework"
  ],
  "display": {
    "imageUrl": "https://netzo.io/images/netzo-symbol-light.svg"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/templates/template-framework-netzo"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-netzo/src/readme.md"
    }
  ],
  "schema": [],
  "item": {
    "_type": "project",
    "fs": {
      "readme.md": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-netzo/src/readme.md"
      },
      "deno.jsonc": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-netzo/src/deno.jsonc"
      },
      "main.tsx": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-netzo/src/main.tsx"
      }
    },
    "configuration": {
      "entrypoint": "main.tsx",
      "envs": {},
      "permissions": {
        "net": true
      }
    }
  }
}

=== deer/netzo/packages/resources/resource-http-jsonplaceholder/item.json
{
  "uid": "resource-http-jsonplaceholder",
  "type": "resource",
  "status": "published",
  "name": "JSONPlaceholder",
  "description": "Resource for the JSONPlaceholder mock API",
  "labels": [
    "mock"
  ],
  "display": {
    "imageUrl": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-jsonplaceholder/icon.webp"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/resources/resource-http-jsonplaceholder"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-jsonplaceholder/src/readme.md"
    }
  ],
  "schema": [],
  "item": {
    "_type": "resource",
    "type": "http",
    "base": {
      "baseURL": "https://jsonplaceholder.typicode.com",
      "headers": {
        "Content-Type": "application/json"
      },
      "authorization": {
        "type": "none"
      }
    }
  }
}

=== deer/netzo/packages/templates/template-framework-oak/item.json
{
  "uid": "template-framework-oak",
  "type": "template",
  "version": "1.0.0",
  "status": "published",
  "name": "Oak",
  "description": "An HTTP server using router to handle POST and GET requests separately. Router by denosaurs is a tiny router framework for Deno Deploy. It can route based on method, route, and has customizable handlers for cases such as no match, errors, or unknown methods.",
  "labels": [
    "framework"
  ],
  "display": {
    "imageUrl": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-oak/icon.webp"
  },
  "links": [
    {
      "rel": "author",
      "href": "https://netzo.io",
      "title": "Netzo"
    },
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/templates/template-framework-oak"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-oak/src/readme.md"
    }
  ],
  "schema": [],
  "item": {
    "_type": "project",
    "fs": {
      "readme.md": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-oak/src/readme.md"
      },
      "deno.jsonc": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-oak/src/deno.jsonc"
      },
      "main.ts": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-framework-oak/src/main.ts"
      }
    },
    "configuration": {
      "entrypoint": "main.ts",
      "envs": {},
      "permissions": {
        "net": true
      }
    }
  }
}

=== deer/netzo/packages/resources/resource-http-pandadoc/item.json
{
  "uid": "resource-http-pandadoc",
  "type": "resource",
  "status": "published",
  "name": "PandaDoc",
  "description": "PandaDoc is a cloud-based document automation platform that helps businesses create, send, track, and e-sign documents.",
  "labels": [
    "productivity"
  ],
  "display": {
    "imageUrl": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-pandadoc/icon.webp"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/resources/resource-http-pandadoc"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-pandadoc/src/readme.md"
    }
  ],
  "schema": [
    {
      "component": "v-text-field",
      "name": "apiKeyWithPrefix",
      "label": "API Key (with prefix)",
      "default": "API-Key {{apiKey}}",
      "hint": "Replace {{apiKey}} with corresponding value."
    }
  ],
  "item": {
    "_type": "resource",
    "type": "http",
    "base": {
      "baseURL": "https://api.pandadoc.com/public/v1",
      "headers": {
        "Content-Type": "application/json"
      },
      "authorization": {
        "type": "apiKey",
        "in": "header",
        "name": "Authorization",
        "value": "{{apiKeyWithPrefix}}"
      }
    }
  }
}

=== deer/netzo/packages/templates/template-css-daisyui/item.json
{
  "uid": "template-css-daisyui",
  "type": "template",
  "version": "1.0.0",
  "status": "published",
  "name": "DaisyUI",
  "description": "A CSS only basic starter template using the DaisyUI library",
  "labels": [
    "css",
    "daisyui"
  ],
  "display": {
    "imageUrl": "https://api.iconify.design/mdi:language-css3.svg?color=%232965f1"
  },
  "links": [
    {
      "rel": "author",
      "href": "https://netzo.io",
      "title": "Netzo"
    },
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/templates/template-css-daisyui"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-css-daisyui/src/readme.md"
    }
  ],
  "schema": [],
  "item": {
    "_type": "project",
    "fs": {
      "readme.md": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-css-daisyui/src/readme.md"
      },
      "deno.jsonc": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-css-daisyui/src/deno.jsonc"
      },
      "main.tsx": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/packages/templates/template-css-daisyui/src/main.tsx"
      }
    },
    "configuration": {
      "entrypoint": "main.tsx",
      "envs": {},
      "permissions": {
        "net": true
      }
    }
  }
}

=== deer/netzo/packages/resources/resource-http-ergastf1/item.json
{
  "uid": "resource-http-ergastf1",
  "type": "resource",
  "version": "1.0.0",
  "status": "published",
  "name": "Ergast F1",
  "description": "Resource for the Ergast F1 API",
  "labels": [
    "mock"
  ],
  "display": {
    "imageUrl": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-ergastf1/icon.webp"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/resources/resource-http-ergastf1"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-ergastf1/src/readme.md"
    }
  ],
  "schema": [],
  "item": {
    "_type": "resource",
    "type": "http",
    "base": {
      "baseURL": "https://ergast.com/api",
      "headers": {
        "Content-Type": "application/json"
      },
      "authorization": {
        "type": "none"
      }
    }
  }
}

=== deer/netzo/packages/resources/resource-http-facturama/item.json
{
  "uid": "resource-http-facturama",
  "type": "resource",
  "status": "published",
  "name": "Facturama",
  "description": "Resource for the Facturama API",
  "labels": [
    "billing"
  ],
  "display": {
    "imageUrl": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-facturama/icon.webp"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/packages/resources/resource-http-facturama"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/packages/resources/resource-http-facturama/src/readme.md"
    }
  ],
  "item": {
    "_type": "resource",
    "type": "http",
    "base": {
      "baseURL": "https://api.facturama.mx",
      "headers": {},
      "basic": {
        "type": "basic",
        "username": "{{username}}",
        "password": "{{password}}"
      }
    }
  }
}
