=== deer/netzo/scripts/template.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "uid": {
      "type": "string"
    },
    "status": {
      "type": "string",
      "enum": [
        "published",
        "requested"
      ]
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string",
      "maxLength": 250
    },
    "labels": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "display": {
      "type": "object",
      "properties": {
        "avatar": {
          "type": "string",
          "format": "uri"
        },
        "color": {
          "type": "string",
          "format": "hexcolor"
        }
      },
      "required": [
        "avatar"
      ]
    },
    "links": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "rel": {
              "type": "string"
            },
            "href": {
              "type": "string",
              "format": "uri"
            },
            "title": {
              "type": "string"
            }
          },
          "required": [
            "rel",
            "href"
          ]
        }
      ]
    },
    "item": {
      "type": "object",
      "properties": {
        "_type": {
          "type": "string"
        },
        "uid": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string",
          "maxLength": 250
        },
        "labels": {
          "type": "array",
          "items": [
            {
              "type": "string"
            }
          ]
        },
        "display": {
          "type": "object",
          "properties": {
            "avatar": {
              "type": "string",
              "format": "uri"
            },
            "color": {
              "type": "string",
              "format": "hexcolor"
            }
          },
          "required": [
            "avatar"
          ]
        },
        "request": {
          "type": "object",
          "properties": {}
        },
        "fs": {
          "type": "object",
          "properties": {
            "readme.md": {
              "type": "object",
              "properties": {
                "url": {
                  "type": "string"
                }
              },
              "required": [
                "url"
              ]
            },
            "main.tsx": {
              "type": "object",
              "properties": {
                "url": {
                  "type": "string"
                }
              },
              "required": [
                "url"
              ]
            }
          },
          "required": [
            "readme.md",
            "main.tsx"
          ]
        },
        "configuration": {
          "type": "object",
          "properties": {
            "entrypoint": {
              "type": "string"
            },
            "envs": {
              "type": "object"
            },
            "permissions": {
              "type": "object",
              "properties": {
                "net": {
                  "type": "boolean"
                }
              },
              "required": [
                "net"
              ]
            }
          },
          "required": [
            "entrypoint",
            "envs",
            "permissions"
          ]
        }
      },
      "required": [
        "_type",
        "uid",
        "fs",
        "configuration"
      ]
    }
  }
}

=== deer/netzo/templates/_requested/api-internal-operations/template.json
{
  "uid": "api-internal-operations",
  "status": "requested",
  "name": "Internal Operations API",
  "description": "Build custom business logic, operations and workflows under a single api. Execute sinple to complex operations, such as sending emails, provisioning users, provisioning infrastructure, and much more via your webhooks and API calls from anywhere.",
  "labels": [
    "department:operations",
    "api:mongodb",
    "category:api",
    "type:operations",
    "type:productivity"
  ],
  "display": {
    "avatar": "https://netzo.io/images/home/apis.svg"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/_requested/api-internal-operations"
    }
  ]
}

=== deer/netzo/templates/sales-dashboard-fresh/template.json
{
  "uid": "sales-dashboard-fresh",
  "status": "published",
  "name": "Sales Dashboard",
  "description": "An HTTP server that serves a sales dashboard to track performance of sales teams in real-time, and provides a variety of metrics to help make informed decisions.",
  "labels": [
    "usecase",
    "dashboard"
  ],
  "display": {
    "avatar": "https://raw.githubusercontent.com/netzo/netzo/main/templates/sales-dashboard-fresh/icon.svg"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/sales-dashboard-fresh"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/templates/sales-dashboard-fresh/src/readme.md"
    }
  ],
  "item": {
    "_type": "project",
    "uid": "sales-dashboard-fresh",
    "fs": {
      "readme.md": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/templates/sales-dashboard-fresh/src/readme.md"
      },
      "import_map.json": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/templates/sales-dashboard-fresh/src/import_map.json"
      },
      "main.tsx": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/templates/sales-dashboard-fresh/src/main.tsx"
      },
      "components/kpi-card.tsx": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/templates/sales-dashboard-fresh/src/components/kpi-card.tsx"
      },
      "components/sales-table.tsx": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/templates/sales-dashboard-fresh/src/components/sales-table.tsx"
      },
      "data/mod.ts": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/templates/sales-dashboard-fresh/src/data/mod.ts"
      }
    },
    "configuration": {
      "entrypoint": "main.tsx",
      "envs": {},
      "permissions": {
        "net": true
      }
    }
  }
}

=== deer/netzo/www/src/public/use-cases/api-department-metrics/template.json
{
  "uid": "api-department-metrics",
  "status": "requested",
  "name": "Department Metrics API",
  "description": "Consolidate department metrics from multiple APIs and standardize, cross-check and cross-create KPIs for any departments, such as sales, marketing, operations, and more. Use you internal API to easily build Business Intelligence dashboards, reports and enhance intradepartment communications.",
  "labels": [
    "department:operations",
    "api:mongodb",
    "category:api",
    "type:business-intelligence",
    "type:productivity"
  ],
  "display": {
    "avatar": "https://netzo.io/images/home/apis.svg"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/_requested/api-department-metrics"
    }
  ]
}

=== deer/netzo/templates/_requested/app-cms-github/template.json
{
  "uid": "app-cms-github",
  "status": "requested",
  "name": "Custom CMS on GitHub",
  "description": "An intuitive content management system (CMS) to easily store and manage digital assets such as images, files, videos and audio in different formats with version control and web hosting via Github.",
  "labels": [
    "department:marketing",
    "department:operations",
    "department:product",
    "department:engineering",
    "api:github",
    "category:app",
    "type:content/cms"
  ],
  "display": {
    "avatar": "https://netzo.io/images/home/admin-panels.svg"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/_requested/app-cms-github"
    }
  ]
}

=== deer/netzo/templates/daisyui/template.json
{
  "uid": "daisyui",
  "status": "published",
  "name": "DaisyUI",
  "description": "A CSS only basic starter template using the DaisyUI library",
  "labels": [
    "css",
    "daisyui"
  ],
  "display": {
    "avatar": "https://api.iconify.design/mdi:language-css3.svg?color=%232965f1"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/daisyui"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/templates/daisyui/src/readme.md"
    }
  ],
  "item": {
    "_type": "project",
    "uid": "daisyui",
    "fs": {
      "readme.md": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/templates/daisyui/src/readme.md"
      },
      "main.tsx": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/templates/daisyui/src/main.tsx"
      }
    },
    "configuration": {
      "entrypoint": "main.tsx",
      "envs": {},
      "permissions": {
        "net": true
      }
    }
  }
}

=== deer/netzo/templates/_requested/dashboard-asset-directory-awss3/template.json
{
  "uid": "dashboard-asset-directory-awss3",
  "status": "requested",
  "name": "Asset Directory for AWS S3",
  "description": "An user-friendly dashboard enhances search and organization capabilities automatically and links to assets stored in AWS S3. This app allows you to view assets stored in your own database.",
  "labels": [
    "department:sales",
    "department:marketing",
    "department:operations",
    "resources:awss3",
    "usecase:productivity",
    "usecase:content/cms"
  ],
  "display": {
    "avatar": "https://netzo.io/images/home/admin-panels.svg"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/_requested/dashboard-asset-directory-awss3"
    }
  ]
}

=== deer/netzo/templates/_requested/workflow-invoice-upload-portal/template.json
{
  "uid": "workflow-invoice-upload-portal",
  "status": "requested",
  "name": "E-Invoice Upload Portal",
  "description": "An e-invoice upload portal that loads and processes mexican electronic invoices versions CFDI3.2, CDFI3.3, CFDI4.0 (PDF and XML), writes data to Google Sheets, and stores files in Google Drive. This app streamlines the invoice handling, naming and submission, increasing efficiency and accuracy.",
  "labels": [
    "department:accounting/finance",
    "api:googlesheets",
    "api:googledrive",
    "type:productivity"
  ],
  "display": {
    "avatar": "https://raw.githubusercontent.com/netzo/netzo/main/templates/_requested/workflow-invoice-upload-portal/icon.svg"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/_requested/workflow-invoice-upload-portal"
    }
  ]
}

=== deer/netzo/templates/_requested/app-nps-sales-customer-support/template.json
{
  "uid": "app-nps-sales-customer-support",
  "status": "requested",
  "name": "NPS for Sales and Support",
  "description": "A dashboard for visualizing and analyzing Net Promoter Score (NPS) data for sales and customer support representatives.",
  "labels": [
    "department:sales",
    "department:customer-support",
    "category:app"
  ],
  "display": {
    "avatar": "https://netzo.io/images/home/bi-dashboards.svg"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/_requested/app-nps-sales-customer-support"
    }
  ]
}
