=== deer/netzo/scripts/template.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "uid": {
      "type": "string"
    },
    "status": {
      "type": "string",
      "enum": [
        "published",
        "requested"
      ]
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string",
      "maxLength": 250
    },
    "labels": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "display": {
      "type": "object",
      "properties": {
        "avatar": {
          "type": "string",
          "format": "uri"
        },
        "color": {
          "type": "string",
          "format": "hexcolor"
        }
      },
      "required": [
        "avatar"
      ]
    },
    "links": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "rel": {
              "type": "string"
            },
            "href": {
              "type": "string",
              "format": "uri"
            },
            "title": {
              "type": "string"
            }
          },
          "required": [
            "rel",
            "href"
          ]
        }
      ]
    },
    "item": {
      "type": "object",
      "properties": {
        "_type": {
          "type": "string"
        },
        "uid": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string",
          "maxLength": 250
        },
        "labels": {
          "type": "array",
          "items": [
            {
              "type": "string"
            }
          ]
        },
        "display": {
          "type": "object",
          "properties": {
            "avatar": {
              "type": "string",
              "format": "uri"
            },
            "color": {
              "type": "string",
              "format": "hexcolor"
            }
          },
          "required": [
            "avatar"
          ]
        },
        "request": {
          "type": "object",
          "properties": {}
        },
        "fs": {
          "type": "object",
          "properties": {
            "readme.md": {
              "type": "object",
              "properties": {
                "url": {
                  "type": "string"
                }
              },
              "required": [
                "url"
              ]
            },
            "main.tsx": {
              "type": "object",
              "properties": {
                "url": {
                  "type": "string"
                }
              },
              "required": [
                "url"
              ]
            }
          },
          "required": [
            "readme.md",
            "main.tsx"
          ]
        },
        "configuration": {
          "type": "object",
          "properties": {
            "entrypoint": {
              "type": "string"
            },
            "envs": {
              "type": "object"
            },
            "permissions": {
              "type": "object",
              "properties": {
                "net": {
                  "type": "boolean"
                }
              },
              "required": [
                "net"
              ]
            }
          },
          "required": [
            "entrypoint",
            "envs",
            "permissions"
          ]
        }
      },
      "required": [
        "_type",
        "uid",
        "fs",
        "configuration"
      ]
    }
  }
}

=== deer/netzo/templates/_requested/admin-panel-custom-crm-mongodb/template.json
{
  "uid": "admin-panel-custom-crm-mongodb",
  "status": "requested",
  "name": "Custom CRM on MongoDB",
  "description": "An adaptable CRM solution designed to cater to the unique requirements of your marketing or sales team with a customizable API interface endpoints for advanced functionality, prospecting and AI integration.",
  "labels": [
    "department:sales",
    "department:marketing",
    "api:mongodb",
    "usecase:admin-panel",
    "usecase:productivity"
  ],
  "display": {
    "avatar": "https://raw.githubusercontent.com/netzo/netzo/main/templates/_requested/admin-panel-custom-crm-mongodb/icon.svg"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/_requested/admin-panel-custom-crm-mongodb"
    }
  ]
}

=== deer/netzo/templates/_requested/website-employee-directory/template.json
{
  "uid": "website-employee-directory",
  "status": "requested",
  "name": "Employee Directory",
  "description": "A web app to quickly find employee data, skills and contact info in a convenient easily accessible interface. This app simplifies matching employees to tasks and projects. Employee data may be stored in any HR system or database and simply streamed, when required.",
  "labels": [
    "usecase:dashboard",
    "usecase:business metrics",
    "department:sales",
    "department:marketing"
  ],
  "display": {
    "avatar": "https://raw.githubusercontent.com/netzo/netzo/main/templates/_requested/website-employee-directory/icon.png"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/_requested/website-employee-directory"
    }
  ]
}

=== deer/netzo/templates/_requested/app-know-your-customer-dashboard/template.json
{
  "uid": "app-know-your-customer-dashboard",
  "status": "requested",
  "name": "Know-Your-Customer Dashboard",
  "description": "Consolidate customer data from any SaaS API, database or spreadsheet for a holistic view of the customer. Enhance team productivity with all the required informationn in one place, while protecting sensitive data from unauthorized individuals.",
  "labels": [
    "department:operations",
    "department:sales",
    "api:googlesheets",
    "api:pipedrive",
    "api:stripe",
    "type:compliance",
    "category:app"
  ],
  "display": {
    "avatar": "https://raw.githubusercontent.com/netzo/netzo/main/templates/_requested/app-know-your-customer-dashboard/icon.svg"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/_requested/app-know-your-customer-dashboard"
    }
  ]
}

=== deer/netzo/templates/_requested/dashboard-nps-sales-customer-support/template.json
{
  "uid": "dashboard-nps-sales-customer-support",
  "status": "requested",
  "name": "NPS for Sales and Support",
  "description": "A dashboard for visualizing and analyzing Net Promoter Score (NPS) data for sales and customer support representatives.",
  "labels": [
    "department:sales",
    "department:customer-support",
    "usecase:dashboard"
  ],
  "display": {
    "avatar": "https://netzo.io/images/home/bi-dashboards.svg"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/_requested/dashboard-nps-sales-customer-support"
    }
  ]
}

=== deer/netzo/templates/_requested/admin-panel-custom-crm-googlesheets/template.json
{
  "uid": "admin-panel-custom-crm-googlesheets",
  "status": "requested",
  "name": "Custom CRM on Google Sheets",
  "description": "An adaptable CRM solution designed to cater to the unique requirements of your marketing or sales team with a customizable API interface endpoints for advanced functionality, prospecting and AI integration.",
  "labels": [
    "department:sales",
    "department:marketing",
    "resources:googlesheets",
    "usecase:admin-panel",
    "usecase:productivity"
  ],
  "display": {
    "avatar": "https://raw.githubusercontent.com/netzo/netzo/main/templates/admin-panel-custom-crm-googlesheets/icon.svg"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/_requested/admin-panel-custom-crm-googlesheets"
    }
  ]
}

=== deer/netzo/templates/_requested/app-know-your-customer/template.json
{
  "uid": "app-know-your-customer",
  "status": "requested",
  "name": "Know-Your-Customer (KYC) Dashboard",
  "description": "Consolidate customer data from any SaaS API, database or spreadsheet for a holistic view of the customer. Enhance team productivity with all the required informationn in one place, while protecting sensitive data from unathorized individuals.",
  "labels": [
    "department:operations",
    "department:sales",
    "api:googlesheets",
    "api:pipedrive",
    "api:stripe",
    "type:compliance",
    "category:app"
  ],
  "display": {
    "avatar": "https://raw.githubusercontent.com/netzo/netzo/main/templates/_requested/app-know-your-customer/icon.svg"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/_requested/app-know-your-customer"
    }
  ]
}

=== deer/netzo/templates/_requested/admin-panel-assets-awss3/template.json
{
  "uid": "admin-panel-assets-awss3",
  "status": "requested",
  "name": "Asset Management for AWS S3",
  "description": "An user-friendly admin panel for managing assets stored in AWS S3. This app allows you to view and manage assets stored in your own database, add advanced functionality and enhance productivity.",
  "labels": [
    "department:sales",
    "department:marketing",
    "department:operations",
    "resources:awss3",
    "usecase:admin-panel",
    "usecase:productivity",
    "usecase:content/cms"
  ],
  "display": {
    "avatar": "https://netzo.io/images/home/admin-panels.svg"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/_requested/admin-panel-assets-awss3"
    }
  ]
}

=== deer/netzo/templates/_requested/workflow-file-upload-router/template.json
{
  "uid": "workflow-file-upload-router",
  "status": "requested",
  "name": "File Upload Router for Drive",
  "description": "A file upload portal that automatically names files with a defined naming convention, logs activity in Google Sheets and stores them in the corresponding locations in Google Drive. This app streamlines file management, handling, searching and retrieval.",
  "labels": [
    "department:operations",
    "api:googlesheets",
    "api:googledrive",
    "usecase:workflow"
  ],
  "display": {
    "avatar": "https://netzo.io/images/home/workflows.svg"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/_requested/workflow-file-upload-router"
    }
  ]
}
