=== deer/netzo/scripts/template.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "uid": {
      "type": "string"
    },
    "status": {
      "type": "string",
      "enum": [
        "published",
        "requested"
      ]
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string",
      "maxLength": 250
    },
    "labels": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "display": {
      "type": "object",
      "properties": {
        "avatar": {
          "type": "string",
          "format": "uri"
        },
        "color": {
          "type": "string",
          "format": "hexcolor"
        }
      },
      "required": [
        "avatar"
      ]
    },
    "links": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "rel": {
              "type": "string"
            },
            "href": {
              "type": "string",
              "format": "uri"
            },
            "title": {
              "type": "string"
            }
          },
          "required": [
            "rel",
            "href"
          ]
        }
      ]
    },
    "item": {
      "type": "object",
      "properties": {
        "_type": {
          "type": "string"
        },
        "uid": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string",
          "maxLength": 250
        },
        "labels": {
          "type": "array",
          "items": [
            {
              "type": "string"
            }
          ]
        },
        "display": {
          "type": "object",
          "properties": {
            "avatar": {
              "type": "string",
              "format": "uri"
            },
            "color": {
              "type": "string",
              "format": "hexcolor"
            }
          },
          "required": [
            "avatar"
          ]
        },
        "request": {
          "type": "object",
          "properties": {}
        },
        "fs": {
          "type": "object",
          "properties": {
            "readme.md": {
              "type": "object",
              "properties": {
                "url": {
                  "type": "string"
                }
              },
              "required": [
                "url"
              ]
            },
            "main.tsx": {
              "type": "object",
              "properties": {
                "url": {
                  "type": "string"
                }
              },
              "required": [
                "url"
              ]
            }
          },
          "required": [
            "readme.md",
            "main.tsx"
          ]
        },
        "configuration": {
          "type": "object",
          "properties": {
            "entrypoint": {
              "type": "string"
            },
            "envs": {
              "type": "object"
            },
            "permissions": {
              "type": "object",
              "properties": {
                "net": {
                  "type": "boolean"
                }
              },
              "required": [
                "net"
              ]
            }
          },
          "required": [
            "entrypoint",
            "envs",
            "permissions"
          ]
        }
      },
      "required": [
        "_type",
        "uid",
        "fs",
        "configuration"
      ]
    }
  }
}

=== deer/netzo/templates/_requested/dashboard-activity-monitor-github/template.json
{
  "uid": "dashboard-activity-monitor-github",
  "status": "requested",
  "name": "Progress Tracker for GitHub",
  "description": "An activity monitoring tool for GitHub repository's activity, owner and collaborators for availability insights for task delegation.",
  "labels": [
    "department:engineering",
    "department:product",
    "api:github",
    "usecase:dashboard",
    "usecase:productivity"
  ],
  "display": {
    "avatar": "https://netzo.io/images/home/bi-dashboards.svg"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/_requested/dashboard-activity-monitor-github"
    }
  ]
}

=== deer/netzo/templates/_requested/app-executive-company-overview/template.json
{
  "uid": "app-executive-company-overview",
  "status": "requested",
  "name": "Executive Data Visualization Dashboard",
  "description": "Consolidate, cross-check and display data from all departments in a single real-time view for executives. Take snapshots, automate reporting and share with stakeholders, live, on-print or email.",
  "labels": [
    "category:apps",
    "type:",
    "type:data analysis",
    "department:marketing",
    "department:sales"
  ],
  "display": {
    "avatar": "https://netzo.io/images/home/bi-dashboards.svg"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/_requested/app-executive-company-overview"
    }
  ]
}

=== deer/netzo/templates/_requested/dashboard-progress-tracker-github/template.json
{
  "uid": "dashboard-progress-tracker-github",
  "status": "requested",
  "name": "Progress Tracker for GitHub",
  "description": "A progress tracking tool for non-technical departments to keep track of development cycles such as upcomming features, bug fixes, versions and issues on GitHub.",
  "labels": [
    "department:engineering",
    "department:product",
    "department:marketing",
    "department:sales",
    "resources:github",
    "usecase:dashboard",
    "usecase:communication/email",
    "usecase:productivity"
  ],
  "display": {
    "avatar": "https://netzo.io/images/home/bi-dashboards.svg"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/_requested/dashboard-progress-tracker-github"
    }
  ]
}

=== deer/netzo/templates/starter-nanossr/template.json
{
  "uid": "starter-nanossr",
  "status": "published",
  "name": "NanoSSR",
  "description": "",
  "labels": [
    "framework"
  ],
  "display": {
    "avatar": "https://raw.githubusercontent.com/netzo/netzo/main/templates/starter-nanossr/icon.webp"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/starter-nanossr"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/templates/starter-nanossr/src/readme.md"
    }
  ],
  "item": {
    "_type": "project",
    "uid": "starter-nanossr",
    "fs": {
      "readme.md": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/templates/starter-nanossr/src/readme.md"
      },
      "main.tsx": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/templates/starter-nanossr/src/main.tsx"
      }
    },
    "configuration": {
      "entrypoint": "main.tsx",
      "envs": {},
      "permissions": {
        "net": true
      }
    }
  }
}

=== deer/netzo/templates/_requested/app-inventory-management-ecommerce/template.json
{
  "uid": "app-inventory-management-ecommerce",
  "status": "requested",
  "name": "E-Commerce Inventory Management",
  "description": "A personalized administration panel to perform manual actions, override or extend e-commerce functionality, and manage inventory. Operations teams can use this to manage their e-commerce sites with advanced control tailored to their needs.",
  "labels": [
    "department:sales",
    "department:operations",
    "category:app",
    "type:productivity"
  ],
  "display": {
    "avatar": "https://netzo.io/images/home/admin-panels.svg"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/_requested/app-inventory-management-ecommerce"
    }
  ]
}

=== deer/netzo/templates/gql/item.json
{
  "uid": "gql",
  "status": "published",
  "name": "GQL",
  "description": "A GraphQL server using gql.",
  "labels": [
    "framework",
    "graphql"
  ],
  "display": {
    "avatar": "https://raw.githubusercontent.com/netzo/netzo/main/templates/gql/icon.webp"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/gql"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/templates/gql/src/readme.md"
    }
  ],
  "item": {
    "_type": "project",
    "uid": "gql",
    "fs": {
      "readme.md": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/templates/gql/src/readme.md"
      },
      "main.tsx": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/templates/gql/src/main.tsx"
      }
    },
    "configuration": {
      "entrypoint": "main.tsx",
      "envs": {},
      "permissions": {
        "net": true
      }
    }
  }
}

=== deer/netzo/templates/template-netzo/item.json
{
  "uid": "netzo",
  "status": "published",
  "name": "Netzo",
  "description": "An HTTP server using netzo that responds with different payload types based on route. Netzo includes a routing and utility library for Deno Deploy. Its route handler signature is simple and easy to understand. Handlers accept a Request and return a Response.",
  "labels": [
    "framework"
  ],
  "display": {
    "avatar": "https://netzo.io/images/netzo-symbol-light.svg"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/netzo"
    },
    {
      "rel": "readme",
      "href": "https://raw.githubusercontent.com/netzo/netzo/main/templates/netzo/src/readme.md"
    }
  ],
  "item": {
    "_type": "project",
    "uid": "netzo",
    "fs": {
      "readme.md": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/templates/netzo/src/readme.md"
      },
      "main.tsx": {
        "url": "https://raw.githubusercontent.com/netzo/netzo/main/templates/netzo/src/main.tsx"
      }
    },
    "configuration": {
      "entrypoint": "main.tsx",
      "envs": {},
      "permissions": {
        "net": true
      }
    }
  }
}

=== deer/netzo/www/src/public/use-cases/app-custom-crm-mongodb/template.json
{
  "uid": "app-custom-crm-mongodb",
  "status": "requested",
  "name": "Custom CRM on MongoDB",
  "description": "An adaptable CRM solution designed to cater to the unique requirements of your marketing or sales team with a customizable API interface endpoints for advanced functionality, prospecting and AI integration.",
  "labels": [
    "department:sales",
    "department:marketing",
    "api:mongodb",
    "category:app",
    "type:productivity"
  ],
  "display": {
    "avatar": "https://raw.githubusercontent.com/netzo/netzo/main/www/src/public/use-cases/app-custom-crm-mongodb/icon.svg"
  },
  "links": [
    {
      "rel": "repository",
      "href": "https://github.com/netzo/netzo/tree/main/templates/_requested/app-custom-crm-mongodb"
    }
  ]
}
